### ISSUE TITLE
[BUG]: Gran Turismo 4 Texture Flickering

### ISSUE THREAD

**Issue by blisstik** [SirMangler/pcsx2#3] opened 2023-05-14 23:58 UTC
### Describe the Bug

The car models have triangular texture flickering issue. I am not sure if this is z-fighting. I am using the same per-game config on original XBSX2 which does not have this issue.

### Reproduction Steps

Go on a track and change to hood or behind the car view.

### PCSX2 Revision

Initial release by SirMangler

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Xbox Series S

### CPU

Stock

### GPU

Stock

**Comment by SirMangler** [comment] 2023-05-15 14:01
Can you confirm if the latest PCSX2 nightlys have this issue? This kind of issue isn't necessarily one we can fix. It may also be a settings related problem.

**Comment by TheRhysWyrill** [comment] 2023-05-15 14:12
This issue is related to Accurate DATE which was removed from PCSX2 a long time ago, fairly certain this does not occur on Vulkan, probably a D3D exclusive issue.

**Comment by blisstik** [comment] 2023-05-15 19:22
The issue does not occur using Software renderer.

On a Macbook Pro M1, the issue does not exist in Hardware renderer mode

Is there a way to patch the issue? I've read other games have this issue as well such as Driver 3 (comments from Discord).

**Comment by GABO1423** [comment] 2023-05-15 21:25
> This issue is related to Accurate DATE which was removed from PCSX2 a long time ago, fairly certain this does not occur on Vulkan, probably a D3D exclusive issue.

FWIW, the issue is not present on the latest AetherSX2 build, although this issue was present there in past builds. Seems to be a UWP issue since it also can't be replicated on PCSX2 proper (even on Windows).

**Comment by blisstik** [comment] 2023-05-17 17:42
I’m wondering the feasibility of backporting it?

https://github.com/PCSX2/pcsx2/pull/7003/commits

**Comment by GABO1423** [comment] 2023-05-21 21:10
I managed to restore the setting in the PR above, here's a sneak peak of the results:

AccurateDATE enabled (current behavior):
![image](https://github.com/SirMangler/pcsx2/assets/35014183/b18125f5-2fe6-4421-b0c0-aada744b31b9)

AccurateDATE disabled:
![image](https://github.com/SirMangler/pcsx2/assets/35014183/7ecd05b0-38d6-4822-abc9-6c28ff687510)

**Comment by GABO1423** [comment] 2023-05-21 21:35
@blisstik Here's a test build, can you verify of #4 is also fixed with the setting off?

[XBSX2.0.zip](https://github.com/SirMangler/pcsx2/files/11525619/XBSX2.0.zip)

**Comment by mansoor909** [comment] 2023-05-22 06:24
Version tested 
1-Gran Turismo 3
2-Gran Turismo 4
3-NBA Street Vol. 2
the problem has been resolved Texture Flickering

*Note NBA Street Vol. 2 works at half speed after repair

**Comment by GABO1423** [comment] 2023-05-22 06:45
> Version tested 1-Gran Turismo 3 2-Gran Turismo 4 3-NBA Street Vol. 2 the problem has been resolved Texture Flickering
> 
> *Note NBA Street Vol. 2 works at half speed after repair

All of these running at default settings? (Minus the new setting being disabled of course)

**Comment by mansoor909** [comment] 2023-05-22 07:04
On my 4k settings

NBA Street Vol. 2

When AccurateDATE is enabled
GPU is used:100% and FPS: 21

When AccurateDATE is disabled
GPU Used:99.2% and FPS:73

**Comment by GABO1423** [comment] 2023-05-22 07:09
> On my 4k settings
> 
> NBA Street Vol. 2
> 
> When AccurateDATE is disabled GPU is used:100% and FPS: 21
> 
> When AccurateDATE is enabled GPU Used:99.2% and FPS:73

1) 4K is definitely not default settings (which is what I asked for) and definitely adds a performance hit since it's very much over the top. There's a reason 1080p is the default.

2) The setting being enabled is basically how the emulator works without the PR, I was under the impression that when you said "working at half speed after repair" you were talking about a performance regression with the setting left enabled.

**Comment by mansoor909** [comment] 2023-05-22 07:15
Tested at 4k resolution
The difference appears when AccurateDATE is disabled or enabled
I will re-test the default settings

**Comment by GABO1423** [comment] 2023-05-22 11:24
> default settings
> 
> When AccurateDATE is disabled GPU is used:33.2% and FPS: 59.94
> 
> When AccurateDATE is enabled GPU is used:21.8% and FPS: 59.94

This confirms the huge performance disparity was because of your settings.

**Closed** 2023-05-22 21:02 UTC
